version: '3.7'

services:
  pgsql:
    image: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    env_file:
      - .env.local
    networks:
      - dbnet

networks:
  dbnet:
    driver: overlay
    attachable: true

volumes:
  pgsql-data: