version: '3.7'

services:
  # Mintos Importer Service
  mintos-importer:
    image: local/mintos-importer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./src/:/usr/local/src/mintos-importer
    env_file:
      - .env.local
    labels:
      - traefik.enable=false
    command: ['sleep', 'infinity']
  # PostgreSQL persistent storage
  pgsql:
    image: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    env_file:
      - .env.local

volumes:
  pgsql-data: