version: '3.7'

services:
  # Mintos Importer Service
  mintos-importer:
    image: local/mintos-importer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
#    volumes:
 #     - ./src/:/usr/local/src/mintos-importer
    env_file:
      - .env.local
    environment:
      - POSTGRES_USER=mintos
      - POSTGRES_PASSWORD=mintos
      - POSTGRES_DB=mintos
      - POSTGRES_SERVER=pgsql
    labels:
      - traefik.enable=false
  pgsql:
    image: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    env_file:
      - .env.local

volumes:
  pgsql-data: