name: Docker image

on: [push, pull_request]

jobs:
  docker-build:
    name: Build & Test Docker image
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Create Docker tag
        id: docker_image_tag
        if: success()
        run: echo ::set-output name=TAG::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
      - name: Build :latest Docker image
        if: success()
        run: docker build -t ${{ steps.docker_image_tag.outputs.TAG }}:latest ./
      - name: Test Docker entrypoint
        if: success()
        run: docker run --env-file .env.local ${{ steps.docker_image_tag.outputs.TAG }} true
      - name: Initialize Docker Swarm
        if: success()
        run: docker swarm init
      - name: Deploy Docker Swarm Stack
        if: success()
        run: docker stack deploy -c docker-stack.test.yaml TEST
      - name: Check PostgreSQL container
        if: success()
        run: |
          CONTAINER_ID=$(docker ps --filter name=pgsql -q -a)
          STATUS=$(docker inspect ${CONTAINER_ID} --format='{{.State.Status}}')
          if [ ${STATUS} != "running" ] ; then echo ${STATUS}; exit 1; else exit 0; fi