name: Docker image

on: [push, pull_request]

jobs:
  docker-build:
    name: Build & Test Docker image
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Create Docker tag
        id: docker_image_tag
        if: success()
        run: echo ::set-output name=TAG::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
      - name: Build :latest Docker image
        if: success()
        run: docker build -t ${{ steps.docker_image_tag.outputs.TAG }}:latest ./
      - name: Test Docker entrypoint
        if: success()
        run: docker run --env-file .env.local ${{ steps.docker_image_tag.outputs.TAG }} true
      - name: Start PostgreSQL
        if: success()
        run: docker run --env-file .env.local --name pgsql -d postgres
      - name: Wait for PostgreSQL Start
        if: success()
        run: until( [ $(docker inspect pgsql --format '{{.State.Status}}') == "running" ] ); do sleep 1; done
      - name: Test database migrations
        if: success()
        run: docker run --link pgsql --env-file .env.local ${{ steps.docker_image_tag.outputs.TAG }} alembic-3 upgrade head